In [20]:
import keras 
import numpy as np
from numpy import genfromtxt

In [21]:
data = genfromtxt('../DATA/bank_note_data.txt',delimiter=",")

In [22]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [23]:
labels=data[:,4]

In [24]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [25]:
features=data[:,:4]

In [26]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [27]:
X=features
y=labels

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [31]:
scaler_object=MinMaxScaler()

In [32]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [33]:
scaled_x_train=scaler_object.transform(X_train)

In [35]:
scaled_x_test=scaler_object.transform(X_test)

In [36]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
model=Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))


model.add(Dense(1,activation='sigmoid'))

In [41]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [43]:
model.fit(scaled_x_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.1681 - accuracy: 0.9499
Epoch 2/50
 - 0s - loss: 0.1637 - accuracy: 0.9554
Epoch 3/50
 - 0s - loss: 0.1596 - accuracy: 0.9532
Epoch 4/50
 - 0s - loss: 0.1553 - accuracy: 0.9565
Epoch 5/50
 - 0s - loss: 0.1512 - accuracy: 0.9565
Epoch 6/50
 - 0s - loss: 0.1475 - accuracy: 0.9565
Epoch 7/50
 - 0s - loss: 0.1451 - accuracy: 0.9554
Epoch 8/50
 - 0s - loss: 0.1412 - accuracy: 0.9587
Epoch 9/50
 - 0s - loss: 0.1377 - accuracy: 0.9619
Epoch 10/50
 - 0s - loss: 0.1343 - accuracy: 0.9576
Epoch 11/50
 - 0s - loss: 0.1313 - accuracy: 0.9597
Epoch 12/50
 - 0s - loss: 0.1287 - accuracy: 0.9619
Epoch 13/50
 - 0s - loss: 0.1255 - accuracy: 0.9630
Epoch 14/50
 - 0s - loss: 0.1227 - accuracy: 0.9630
Epoch 15/50
 - 0s - loss: 0.1201 - accuracy: 0.9641
Epoch 16/50
 - 0s - loss: 0.1175 - accuracy: 0.9641
Epoch 17/50
 - 0s - loss: 0.1148 - accuracy: 0.9695
Epoch 18/50
 - 0s - loss: 0.1124 - accuracy: 0.9674
Epoch 19/50
 - 0s - loss: 0.1103 - accuracy: 0.9695
Epoch 20/50
 - 0s - l

In [46]:
model.metrics_names

['loss', 'accuracy']

In [47]:
from sklearn.metrics import confusion_matrix,classification_report

In [48]:
predictions= model.predict_classes(scaled_x_test)

In [49]:
confusion_matrix(y_test,predictions)

array([[253,   4],
       [  5, 191]], dtype=int64)

In [51]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       257
         1.0       0.98      0.97      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



In [52]:
model.save('mysupermodel.h5')

In [54]:
from keras.models import load_model

In [55]:
model= load_model('mysupermodel.h5')

In [56]:
model.predict_classes(scaled_x_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    